---
collections:

  # https://galaxy.ansible.com/community/general
  # https://docs.ansible.com/ansible/latest/collections/community/general/index.html#plugins-in-community-general
  - name: community.general
    version: 8.2.0
    source: https://galaxy.ansible.com

  # https://galaxy.ansible.com/community/docker
  # https://docs.ansible.com/ansible/latest/collections/community/docker/index.html#plugins-in-community-docker
  - name: community.docker
    version: 3.5.0
    source: https://galaxy.ansible.com

  # https://galaxy.ansible.com/ansible/posix
  # https://github.com/ansible-collections/ansible.posix/tree/main/docs
  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com


roles:
  # https://galaxy.ansible.com/geerlingguy/docker
  # https://github.com/geerlingguy/ansible-role-docker
  - src: geerlingguy.docker
    version: 7.0.2


  # https://galaxy.ansible.com/geerlingguy/node_exporter
  # https://github.com/geerlingguy/ansible-role-node_exporter
  - src: geerlingguy.node_exporter
    version: 2.1.0
