---
- hosts: node-0
  become: true
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}" --apiserver-cert-extra-sans="{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"  --node-name node-0 --pod-network-cidr=192.168.40.0/24
  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config
  - name: Install calico pod network
    become: false
    command: kubectl create -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml
  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command
  handlers:
    - name: docker status
      service: name=docker state=started

- hosts: nodes
  become: true
  tasks:
  - name: Run a command to join cluster
    shell: "{{ hostvars['node-0']['join_command'].stdout_lines | first }}"
  handlers:
    - name: docker status
      service: name=docker state=started
