- hosts: all
  become: true
  vars:
    docker_users: [ "vagrant" ]
    docker_install_compose: false
  roles:
    - geerlingguy.docker
  tasks:
    - name: Install docker python
      apt:
        pkg:
        - python3-docker
        - python-docker
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: 0755
        timeout: 100
